services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        VITE_API_URL: http://${SERVER_HOST}:${SERVER_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_API_URL=http://${SERVER_HOST}:${SERVER_PORT}
    ports:
      - "4242:80"
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_NAME=${SERVER_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PROVIDER=${DB_PROVIDER}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - LOGS_PATH=${LOGS_PATH}
      - RATE_LIMITER_REQUEST_COUNT=${RATE_LIMITER_REQUEST_COUNT}
      - RATE_LIMITER_TIME_WINDOW_MS=${RATE_LIMITER_TIME_WINDOW_MS}
      - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    restart: always

  database:
    image: mysql:8.3.0
    environment:
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "database" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

networks:
  app-network:

volumes:
  db_data: